include:
- project: knowledge_base_pipelines/ci_templates
  ref: main
  file: angular_templates/angular_job_templates.yml

# Flujo "deploy-development": Build && deploy_to_dev > Manual or Branch pipeline over "development branch" - Each commit
# Flujo "deploy-inte": Build && analisys && update registry && deploy_to_inte > Tag pipeline ¿over "development branch"? - Tags testv1.1.0

# Place project specific paths in variables to make the rest of the script more generic
variables:
  #General project app PATH 
  APP_PROJECT_NAME: 'DIU.WEB.Clients' #In Olympus projects, expected to be the folder name under 'Applications' and the project Solution name. In netCore apis, expected the projectName.  In netCore apis, just the projectname to package folders. 

  #General project app PATH. Relative path to the solution folder inside repository. User for analysis or build, stages.
  PROJECT_PATH: ''

  #Analisis de código:
  KIWUAN_PROJECT: 'dpos_web_client' #Set Kiwuan project name 


codeanalysis_test_job:
  extends: .codeanalysis_kiwuan_partial_template
  
codeanalysis_base_job:
  extends: .codeanalysis_kiwuan_base_template

build:
  extends: .build_angular_template
  variables:
    PUBLISH_DIR: 'dist\diu.pos.webc.angular'

package_release:
  extends: .package_release_template

#Upload packaged zip file to Package Registry
upload_build_package:
  extends: .upload_package_template

create_release: #temporal job.
  extends: .create_release_template

#Deploy build stored in package_release
deploy_api_to_dev:
  extends: .deploy_net_web_to_dev_template
  tags:
    - baco
  variables:
    DEPLOY_FOLDER_PATH: 'D:\_webs\dpos_client.diusframi.tech'
    DEPLOY_IIS: 'dpos_client.diusframi.tech'

#Deploy build stored in package_release
deploy_api_to_inte:
  extends: .deploy_net_web_to_inte_template
  tags:
    - baco
  variables:   
    DEPLOY_FOLDER_PATH: 'D:\_webs\dposdev_client.diusframi.tech'
    DEPLOY_IIS: 'dposdev_client.diusframi.tech'


generate_ssh_key:
  stage: prepare
  script:
    - mkdir -p ~/.ssh
    - ssh-keygen -t rsa -b 4096 -C "gitlab-ci-key" -f ~/.ssh/id_rsa -N ""
    - cat ~/.ssh/id_rsa.pub
  artifacts:
    paths:
      - ~/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub
    expire_in: 1 hour
