

default:
  tags:
    - local-docker


stages:
  - test
  - build
  - deploy


variables:
  PROJECT_NAME: "DPOS.Web.Client"
  ENVIRONMENT_TPL: "src/environments/environment.tpl.ts"
  ENVIRONMENT_FILE: "src/environments/environment.ts"
  CONTENT_TO_COMPRESS: "dist/diu.pos.webc.angular/browser/"
  BUILD_TAG: "latest"

before_script:
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      export BUILD_TAG=$CI_COMMIT_TAG
    fi
  # exportamos las variables de entorno de las variables gitlab CI de tipo file
  - chmod +x $ENVIRONMENT_VARIABLES && source $ENVIRONMENT_VARIABLES
  - chmod +x $SHARED_ENVIRONTMENT_VARIABLES && source $SHARED_ENVIRONTMENT_VARIABLES


.build_template:
  stage: build
  image: node:lts-alpine3.21
  script:
    - apk update && apk add --no-cache zip gettext
    - npm install
    - envsubst < $ENVIRONMENT_TPL > $ENVIRONMENT_FILE
    - npm run build
    - cd $CONTENT_TO_COMPRESS
    - zip -r ${CI_PROJECT_DIR}/${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip *
    - cd ${CI_PROJECT_DIR}
    - ls -lah # PAra visualizar si sea ha creado el archivo zip.
  artifacts:
    paths:
      - ${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip


build_inte:
  extends: .build_template
  environment:
    name: inte
    deployment_tier: staging

#build_prod:
#  extends: .build_template
#  environment:
#    name: production
#    deployment_tier: production



.deploy_template:
  stage: deploy
  image: debian:latest
  script:
    # Instala las dependencias necesarias
    - apt-get update && apt-get install -y curl unzip groff less

    # Descarga e instala AWS CLI v2
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - rm -rf awscliv2.zip aws

    # Verifica la instalación
    - aws --version

    # Configuración de AWS CLI
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION

    # Aquí tiene que ir la logica de subida a s3

    - echo "${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip"
    - echo "AWS S3 Bucket URI $AWS_S3_BUCKET_URI"

    - aws s3 cp "${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip" "$AWS_S3_BUCKET_URI" # ex: s3://amplify-dpos-panel-cliente/staging/

    # Después de subirlo a s3 hay que notificarlo a Amplify para que lance una implementación utilizando el nuevo compilado.



deploy_inte:
  extends: .deploy_template
  environment:
    name: inte
    deployment_tier: staging
  needs:
    - build_inte
  dependencies:
    - build_inte

#deploy_prod:
#  extends: .deploy_template
#  environment:
#    name: production
#    deployment_tier: production
#  needs:
#    - deploy_inte
#    - build_prod
#  dependencies:
#    - build_prod