image: alpine:3.21

default:
  tags:
    - local-docker


stages:
  - test
  - build
  - deploy_inte
  - deploy_prod


variables:
  PROJECT_NAME: DPOS.Web.Client
  ENVIRONMENT_TPL: src/environments/environment.tpl.ts
  ENVIRONMENT_FILE: src/environments/environment.ts
  CONTENT_TO_COMPRESS: dist/diu.pos.webc.angular/browser/*
  BUILD_TAG: latest

before_script:
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      export BUILD_TAG=$CI_COMMIT_TAG
    fi
  # exportamos las variables de entorno de las variables gitlab CI de tipo file
  - chmod +x $ENVIRONMENT_VARIABLES && source $ENVIRONMENT_VARIABLES


.build_template:
  stage: build
  image: node:lts-alpine3.21
  script:
    - apk update && apk add --no-cache zip gettext
    - npm install
    - envsubst < $ENVIRONMENT_TPL > $ENVIRONMENT_FILE
    - npm run build
    - zip -r ${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip $CONTENT_TO_COMPRESS
    - ls -lah # PAra visualizar si sea ha creado el archivo zip.
  artifacts:
    paths:
      - ${PROJECT_NAME}.${CI_ENVIRONMENT_SLUG}.${BUILD_TAG}.zip


build_inte:
  extends: .build_template
  environment:
    name: inte
    deployment_tier: staging

build_prod:
  extends: .build_template
  environment:
    name: production
    deployment_tier: production






