const API = 'api';

export const RestRoutes = {
  CONTACTS: `${API}/Contacts`,
  CONTACTS_GETSH: `${API}/Contacts/GetSH/{page}`,
  LANGUAGES: `${API}/Languages`,
  USER: `${API}/user`,
  AUTH: `${API}/auth`,
  AUTHPU:`${API}/auth/portalusers`,
  ALERTS: `${API}/Alerts`,
  ALERTS_SUMMARY: `${API}/Alerts/summaries`,
  ALERTS_SUMMARY_SEARCH: `${API}/Alerts/search/summary/page`,
  ALERTS_SUMMARY_PAGINATED: `${API}/Alerts/summaries/page`,
  ACTIONCONFIGURATIONTEMPLATES_GETSH: `${API}/ActionConfigurationTemplates/Search`,
  ACTIONCONFIGURATIONTEMPLATES_DELETED: `${API}/ActionConfigurationTemplates/{actionConfigurationTemplateID}/{lastUpdateBy}`,
  ACTIONCONFIGURATIONTEMPLATES_GETONE: `${API}/ActionConfigurationTemplates/{actionConfigurationTemplateID}`,
  ACTIONCONFIGURATIONTEMPLATES_ADDUPDATE: `${API}/ActionConfigurationTemplates/`,
  ALERTCONFIGURATION_GETSH_PAGINATED: `${API}/AlertConfigurations/{portalId}/search/page/{page}`,
  ALERTCONFIGURATION_GETONE: `${API}/AlertConfigurations/{alertConfigurationGuid}`,
  ALERTCONFIGURATION_ADDUPDATECONFIGURATIONANDVERSIONS: `${API}/AlertConfigurations/`,
  ALERTCONFIGURATION_ADDUPDATE: `${API}/AlertConfigurations/AddUpdate`,
  ALERTCONFIGURATIONVERSIONS_GETONE: `${API}/AlertsConfigurationVersions/{alertConfigurationVersionGUID}`,
  ALERTCONFIGURATIONVERSIONS_GETSH: `${API}/AlertsConfigurationVersions/Search/`,
  ALERT_CONFIGURATIONS_PROPERTIES: `${API}/AlertConfigurations/properties`,
  ALERT_CONFIGURATIONS_UPDATE_FALSE_POSITIVE: `${API}/AlertConfigurations/update/alert/state/false-positive`,
  ALERT_CONFIGURATIONS_UPDATE_OK: `${API}/AlertConfigurations/update/alert/state/ok`,
  BALANCE_ID:`${API}/Balances/`,
  PW_RECOVER: `${API}/auth/portalusers/password/recover`,
  PW_RESET: `${API}/auth/portalusers/password/reset`,
  PW_CONDITIONS: `${API}/auth/portalusers/password/properties`,
  SALES_INFO:`${API}/Orders?size=`,
  SALES_INFO2:`&offset=0`,
  SALES_INFO3:`&qs={"and":`,
  SALES_DETAILS:`${API}/Orders/`,
  BALANCES_INFO:`${API}/Balances?size=`,
  BALANCES_DETAILS:`${API}/Balances/`,
  ARQUEO_X:`${API}/Balances/generate/arqueo-x?fromDate=`,
  ARQUEO_X2:`&toDate=`,
  SALES_REPORT:`${API}/Orders/generate/sales-report?fromDate=`,
  SALES_REPORT2:`&toDate=`,
  TERMINAL_LIST:`${API}/commerces/1125/Terminals`,
  ORDER_AGGREGATION:`${API}/Orders/aggregate`,
  CASH_AGGREGATION:`${API}/CashMovements/aggregate`,
  PORTALUSERS_COMMERCES:`${API}/PortalUsers/commerces`,
  PORTALUSERS_TERMINALS:`${API}/PortalUsers/terminals`,
  PORTALUSERS_LOGIN:`${API}/auth/portalusers/login`
}
